version: '3'
services:
  api:
    ports:
      - "9000:9000"
    environment:
      - WSP_API_PUBLIC_URL=http://localhost:9000
      # Obtained from: https://www.microsoft.com/cognitive-services/en-US/subscriptions
      - WSP_BING_API_KEY=change_me
      - APPLICATION_SECRET=change_me # Some random string
  web:
    build:
      args:
        api_host: "http://localhost:9000"
    ports:
      - "8080:8080"
